### PR TITLE
Adds URL to get_matches()

### PR DESCRIPTION
**Pull request by grantephross**
Allows you to get matchid/match page url info out of the API for upcoming matches

### CODE REVIEW

**Comment by zGrav** [comment]
Thanks!

**Comment by SocksPls** [comment]
updated readme to include https://github.com/SocksPls/hltv-api/commit/156c5b94e1f4d59f04ca9184c2bb591b9536486d

**Comment by zGrav** [comment]
ty, forgot that bit

**Comment by grantephross** [comment]
Thank you, took me a while to figure out but was pretty simple once I knew what I was looking at :D :D I'm using it for an HLTV Discord bot that will post a link and match information for the next match coming up for that persons team. Maybe use it to auto create discord server events as well. 

Your API is a huge help!

**Comment by grantephross** [comment]
This did introduce a bug 
image
we are getting the rest of the url past the match id incorrect. im trying to think of how to fix this

**Comment by zGrav** [comment]
> This did introduce a bug image we are getting the rest of the url past the match id incorrect. im trying to think of how to fix this

Thanks for the catch! fixed in https://github.com/SocksPls/hltv-api/commit/23873657abb6268d86155c331a5c65bd702747a4

**Pull request merged**
